{
  "dataset_name": "camargo",
  "dataset_path": "J:/CAMARGO_ET_AL_J_BIOMECH_DATASET/",
  "dl_dataset_path": "J:/CAMARGO_ET_AL_J_BIOMECH_DATASET/MiniDataset/",
  "dl_dataset": "levelgroundrampstair_imuik_AB06AB07AB08AB09AB10AB11AB12AB13AB14AB15AB16AB17AB18AB19AB20AB21AB23AB24AB25.p",
  "selected_data_types": ["baseline"],
  "selected_data_status": ["imu"],
  "label_headers": ["Header", "Label", "subject", "trialType", "trialNum", "trialStarts", "trialEnds", "leadingLegStart", "leadingLegStop", "turn", "speed", "transLegAscent", "transLegDescent", "rampInclide", "stairHeight"],
  "imu_features": ["Accel_X","Accel_Y", "Accel_Z",
                        "Gyro_X", "Gyro_Y", "Gyro_Z"],
  "imu_sensors": ["foot", "shank", "thigh", "trunk"],
  "selected_sensors": ["foot","shank","thigh"],
  "selected_imu_features": ["Accel_X","Accel_Y", "Accel_Z",
                        "Gyro_X", "Gyro_Y", "Gyro_Z"],
  "selected_opensim_labels": ["hip_flexion_r", "knee_angle_r", "ankle_angle_r"],
  "selected_trial_type": ["levelground","ramp", "stair"],
  "selected_trial_type2": [["levelground1","levelground2","rampascent", "rampdescent","stairascent","stairdescent"]],
  "selected_activity_label": ["all_split"],
  "segmentation_method": "fixedwindow",
  "data_transformer": {"data_transformer_method": "StandardScaler", "data_transformer_by": "by_var"},
  "target_padding_length": 256,
  "resample": true,
  "opensim_filter": false,
  "imu_filter": false,

  "load_model": false,
  "save_model": false,
  "tuning": false,
  "individual_plot": false,

  "name": "sweep_models_subjects_all_activities_all_remove_outlier_models",
  "method": "grid",
  "metric":{
    "name": "Validation Loss",
    "goal": "minimize",
  },

  "parameters": {
    "method":
      {
        "distribution": "categorical",
        "values": ["baseline"]
      },
    "selected_sensors":
      {
        "distribution": "categorical",
        "values": [["thigh", "shank", "foot"]]
      },
    "selected_opensim_labels":
      {
        "distribution": "categorical",
        "values": [["hip_flexion_r", "knee_angle_r", "ankle_angle_r"]]
      },
    "selected_trial_type":
      {
        "distribution": "categorical",
        "values": [["levelground","ramp", "stair"]]
      },
    "selected_trial_type2":
      {
        "distribution": "categorical",
        "values": [["levelground1","levelground2","rampascent", "rampdescent","stairascent","stairdescent"]]
      },
    "selected_activity_label":
      {
        "distribution": "categorical",
        "values": [["all_split"]]
      },
    "target_padding_length": {
      "distribution": "categorical",
      "values":[256]
    },
    "resample":
      {
        "distribution": "categorical",
        "values": [true]
      },
    "rotation":
      {
        "distribution": "categorical",
        "values": [false]
      },
    "train_subjects":
      {
        "distribution": "categorical",
        "values": [["AB06", "AB07", "AB08", "AB09","AB10", "AB11", "AB12", "AB13", "AB14", "AB15", "AB16", "AB17", "AB18",
                    "AB19", "AB20", "AB21"]]
      },
    "train_activity":
      {
        "distribution": "categorical",
        "values": [["levelground1","levelground2","rampascent", "rampdescent","stairascent","stairdescent"]]
      },
    "test_subjects":
      {
        "distribution": "categorical",
        "values": [["AB23", "AB24", "AB25"]]
      },
    "test_activity":
      {
        "distribution": "categorical",
        "values": [["levelground1","levelground2","rampascent", "rampdescent","stairascent","stairdescent"]]
      },
    "model_name":
      {
        "distribution": "categorical",
        "values": ["transformertsai","bilstm", "hernandez2021cnnlstm"]
      },
    "tsai_d_model": {
      "distribution": "categorical",
      "values": [256]
    },
    "tsai_n_heads": {
      "distribution": "categorical",
      "values": [16]
    },
    "tsai_d_ff": {
      "distribution": "categorical",
      "values": [128]
    },
    "tsai_n_layers": {
      "distribution": "categorical",
      "values":  [2]
    },
    "tsai_res_dropout_p": {
      "distribution": "categorical",
      "values": [0.2]
    },
    "tsai_fc_dropout_p": {
      "distribution": "categorical",
      "values": [0.8]
    },
    "bilstm_hidden_size":
      {
        "distribution": "categorical",
        "values": [128]
      },
    "bilstm_num_layers":
      {
        "distribution": "categorical",
        "values": [2]
      },
    "bilstm_dropout_p":
      {
        "distribution": "categorical",
        "values": [0.2]
      },
    "EncoderCNN_conv_l1_out_channel":
      {
        "distribution": "categorical",
        "values": [16]
      },
    "EncoderCNN_conv_l1_kernel_size":
      {
        "distribution": "categorical",
        "values": [[10,3]]
      },
    "EncoderCNN_conv_l1_dropout":
      {
        "distribution": "categorical",
        "values": [0.2]
      },
    "EncoderCNN_conv_l2_out_channel":
      {
        "distribution": "categorical",
        "values": [32]
      },
    "EncoderCNN_conv_l2_kernel_size":
      {
        "distribution": "categorical",
        "values": [[10,3]]
      },
    "EncoderCNN_conv_l2_dropout":
      {
        "distribution": "categorical",
        "values": [0.2]
      },
    "DecoderLSTM_hidden_size":
      {
        "distribution": "categorical",
        "values": [128]
      },
    "DecoderLSTM_num_layers":
      {
        "distribution": "categorical",
        "values": [2]
      },
    "DecoderLSTM_dropout_p":
      {
        "distribution": "categorical",
        "values": [0.2]
      },
    "optimizer_name":
      {
        "distribution": "categorical",
        "values": ["Adam"]
      },
    "l2_weight_decay_status":
      {
        "distribution": "categorical",
        "values": [true]
      },
    "l2_weight_decay":
      {
        "distribution": "categorical",
        "values": [0.001]
      },
    "learning_rate":
      {
        "distribution": "categorical",
        "values": [0.001]
      },
    "n_epoch":
      {
        "distribution": "categorical",
        "values": [25, 2]
      },
    "batch_size":
      {
        "distribution": "categorical",
        "values": [50]
      },
    "nfold":
      {
        "distribution": "categorical",
        "values": [5]
      },
  }
}